/**
 * Standalone Anchor Provider + Program Loading
 *
 * Creates an Anchor provider and Program instances manually, without relying
 * on `anchor.workspace` which only works in test contexts. This is the
 * foundation for all deployment scripts (initialize.ts, verify.ts).
 *
 * Why standalone? `anchor.workspace` auto-loads programs from Anchor.toml,
 * but only works when run via `anchor test`. Deployment scripts run via
 * `npx tsx` and need explicit provider/program construction.
 *
 * Configuration via env vars:
 *   CLUSTER_URL - Solana RPC endpoint (default: http://localhost:8899)
 *   WALLET      - Path to wallet keypair JSON (default: keypairs/devnet-wallet.json)
 *   COMMITMENT  - Transaction commitment level (default: "confirmed")
 *                 Use "finalized" for devnet/mainnet to guarantee permanence
 */

import * as anchor from "@coral-xyz/anchor";
import { Connection, Keypair } from "@solana/web3.js";
import * as fs from "fs";
import * as path from "path";

// Import type definitions for all 7 programs
// These are generated by `anchor build` and live in target/types/
import { Amm } from "../../../target/types/amm";
import { TransferHook } from "../../../target/types/transfer_hook";
import { TaxProgram } from "../../../target/types/tax_program";
import { EpochProgram } from "../../../target/types/epoch_program";
import { Staking } from "../../../target/types/staking";
import { ConversionVault } from "../../../target/types/conversion_vault";
import { BondingCurve } from "../../../target/types/bonding_curve";

/**
 * All 7 protocol programs, typed for IDE autocompletion and safety.
 */
export interface Programs {
  amm: anchor.Program<Amm>;
  transferHook: anchor.Program<TransferHook>;
  taxProgram: anchor.Program<TaxProgram>;
  epochProgram: anchor.Program<EpochProgram>;
  staking: anchor.Program<Staking>;
  conversionVault: anchor.Program<ConversionVault>;
  bondingCurve: anchor.Program<BondingCurve>;
}

/**
 * Create an Anchor provider from cluster URL + wallet keypair.
 *
 * Why AnchorProvider and not just Connection?
 * - Anchor's Program.methods.*.rpc() requires a provider with a wallet
 * - The provider handles signing, sending, and confirming transactions
 * - "confirmed" commitment balances speed and reliability for deployment
 *
 * @param clusterUrl - RPC endpoint (default: CLUSTER_URL env var or localhost)
 * @param walletPath - Path to wallet keypair JSON (default: WALLET env var or devnet-wallet)
 * @returns Configured AnchorProvider ready for transaction submission
 *
 * Commitment levels:
 * - "processed" (fastest, least reliable -- not recommended)
 * - "confirmed" (default, good for localnet and testing)
 * - "finalized" (slowest ~6s, guarantees permanence -- use for devnet/mainnet deployments)
 */
export function loadProvider(
  clusterUrl?: string,
  walletPath?: string
): anchor.AnchorProvider {
  const url = clusterUrl || process.env.CLUSTER_URL || "http://localhost:8899";
  const keyPath = walletPath || process.env.WALLET || "keypairs/devnet-wallet.json";

  // Resolve wallet path relative to project root (where scripts are run from)
  const resolvedKeyPath = path.isAbsolute(keyPath)
    ? keyPath
    : path.resolve(process.cwd(), keyPath);

  if (!fs.existsSync(resolvedKeyPath)) {
    throw new Error(
      `Wallet keypair not found at: ${resolvedKeyPath}\n` +
      `Create one with: solana-keygen new -o ${keyPath}`
    );
  }

  // Load the keypair from JSON file (standard Solana keypair format: array of 64 bytes)
  const secretKey = JSON.parse(fs.readFileSync(resolvedKeyPath, "utf8"));
  const wallet = new anchor.Wallet(
    Keypair.fromSecretKey(new Uint8Array(secretKey))
  );

  // Read commitment level from env var, defaulting to "confirmed" for backward compatibility.
  // On devnet/mainnet, set COMMITMENT=finalized to guarantee transaction permanence.
  // The extra latency (~6s vs ~0.5s per tx) is acceptable for one-time deployment.
  const commitment = (process.env.COMMITMENT as anchor.web3.Commitment) || "confirmed";
  const connection = new Connection(url, commitment);

  const provider = new anchor.AnchorProvider(connection, wallet, {
    preflightCommitment: commitment,
    commitment: commitment,
  });

  return provider;
}

/**
 * Load all 7 protocol programs from their IDL files.
 *
 * Why load IDLs from files instead of using anchor.workspace?
 * - anchor.workspace only works in `anchor test` context
 * - Manual IDL loading works from any context (npx tsx, node, etc.)
 * - We get full type safety via the generic Program<T> type parameter
 *
 * The IDL files are generated by `anchor build` and contain the program's
 * address, instructions, accounts, and types. The Program constructor
 * derives the program ID from the IDL's "address" field.
 *
 * @param provider - AnchorProvider for RPC communication and signing
 * @returns Object with all 6 typed Program instances
 */
export function loadPrograms(provider: anchor.AnchorProvider): Programs {
  // Resolve IDL directory relative to this file's location
  // __dirname = scripts/deploy/lib/ -> ../../../target/idl/
  const idlDir = path.resolve(__dirname, "../../../target/idl");

  function loadIdl(name: string): any {
    const idlPath = path.join(idlDir, `${name}.json`);
    if (!fs.existsSync(idlPath)) {
      throw new Error(
        `IDL file not found: ${idlPath}\n` +
        `Run 'anchor build' first to generate IDL files.`
      );
    }
    return JSON.parse(fs.readFileSync(idlPath, "utf8"));
  }

  // Load each program with its corresponding IDL and type
  // The Program<T> generic provides full type safety for .methods.*, .account.*, etc.
  const amm = new anchor.Program<Amm>(loadIdl("amm"), provider);
  const transferHook = new anchor.Program<TransferHook>(loadIdl("transfer_hook"), provider);
  const taxProgram = new anchor.Program<TaxProgram>(loadIdl("tax_program"), provider);
  const epochProgram = new anchor.Program<EpochProgram>(loadIdl("epoch_program"), provider);
  const staking = new anchor.Program<Staking>(loadIdl("staking"), provider);
  const conversionVault = new anchor.Program<ConversionVault>(loadIdl("conversion_vault"), provider);
  const bondingCurve = new anchor.Program<BondingCurve>(loadIdl("bonding_curve"), provider);

  return { amm, transferHook, taxProgram, epochProgram, staking, conversionVault, bondingCurve };
}
