/**
 * Deployment Configuration Schema
 *
 * TypeScript types and validation for `deployments/{cluster}.json`.
 * This file defines the canonical schema for the single-source-of-truth
 * deployment config that contains every protocol address.
 *
 * Schema versioning: `schemaVersion` field allows future evolution
 * without breaking existing consumers.
 *
 * Source: .planning/phases/91-deploy-config-foundation/91-01-PLAN.md
 */

// =============================================================================
// Interfaces
// =============================================================================

/**
 * Pool configuration: pool PDA + two vault accounts.
 */
export interface PoolEntry {
  pool: string;
  vaultA: string;
  vaultB: string;
}

/**
 * Bonding curve PDA set for a single token faction.
 */
export interface CurvePdaEntry {
  curveState: string;
  tokenVault: string;
  solVault: string;
  taxEscrow: string;
}

/**
 * Authority tracking: who controls the protocol and when was it transferred.
 */
export interface AuthorityInfo {
  /** The original deployer wallet */
  deployer: string;
  /** Squads multisig vault (null until authority is transferred) */
  squadsVault: string | null;
  /** ISO timestamp of authority transfer (null until transferred) */
  transferredAt: string | null;
}

/**
 * Optional metadata URIs for token mint metadata.
 */
export interface MetadataInfo {
  crime: string;
  fraud: string;
  profit: string;
}

/**
 * Complete deployment configuration for a cluster.
 *
 * This is the single source of truth for all protocol addresses.
 * Generated by `generate-deployment-json.ts` or at the end of `initialize.ts`.
 * Consumed by `generate-constants.ts`, `verify.ts`, crank runner, and other tools.
 */
export interface DeploymentConfig {
  /** Schema version for forward compatibility. Current: 1 */
  schemaVersion: number;

  /** ISO timestamp when this config was generated */
  generatedAt: string;

  /** Cluster name: "devnet" or "mainnet" */
  cluster: string;

  /** All 7 program IDs */
  programs: {
    amm: string;
    transferHook: string;
    taxProgram: string;
    epochProgram: string;
    staking: string;
    conversionVault: string;
    bondingCurve: string;
  };

  /** All 3 token mint addresses */
  mints: {
    crime: string;
    fraud: string;
    profit: string;
  };

  /** All singleton PDA addresses */
  pdas: {
    adminConfig: string;
    swapAuthority: string;
    taxAuthority: string;
    epochState: string;
    stakePool: string;
    escrowVault: string;
    stakeVault: string;
    whitelistAuthority: string;
    carnageFund: string;
    carnageSolVault: string;
    carnageCrimeVault: string;
    carnageFraudVault: string;
    carnageSigner: string;
    stakingAuthority: string;
    wsolIntermediary: string;
    vaultConfig: string;
    vaultCrime: string;
    vaultFraud: string;
    vaultProfit: string;
  };

  /** AMM pool configs (2 SOL pools) */
  pools: {
    crimeSol: PoolEntry;
    fraudSol: PoolEntry;
  };

  /** Bonding curve PDAs per faction */
  curvePdas: {
    crime: CurvePdaEntry;
    fraud: CurvePdaEntry;
  };

  /** Hook ExtraAccountMetaList PDAs per mint */
  hookAccounts: {
    crime: string;
    fraud: string;
    profit: string;
  };

  /** Address Lookup Table address (null if not created yet) */
  alt: string | null;

  /** Treasury wallet address */
  treasury: string;

  /** Authority tracking */
  authority: AuthorityInfo;

  /** Optional token metadata URIs */
  metadata?: MetadataInfo;
}

// =============================================================================
// Validation
// =============================================================================

/**
 * Base58 character set for address validation.
 * Solana addresses are 32-44 character base58 strings.
 */
const BASE58_REGEX = /^[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{32,44}$/;

/**
 * Validate that a string is a valid base58 Solana address.
 */
function isValidBase58Address(addr: string): boolean {
  return BASE58_REGEX.test(addr);
}

/**
 * Validate a DeploymentConfig object.
 *
 * Checks:
 * - All required top-level fields are present
 * - schemaVersion is a number
 * - All address strings are valid base58 (32-44 chars)
 *
 * @param config - Object to validate
 * @returns Array of error messages (empty = valid)
 */
export function validateDeploymentConfig(config: unknown): string[] {
  const errors: string[] = [];

  if (!config || typeof config !== "object") {
    return ["Config is not an object"];
  }

  const c = config as Record<string, unknown>;

  // Check top-level required fields
  const requiredFields = [
    "schemaVersion", "generatedAt", "cluster", "programs",
    "mints", "pdas", "pools", "curvePdas", "hookAccounts",
    "treasury", "authority",
  ];
  for (const field of requiredFields) {
    if (!(field in c)) {
      errors.push(`Missing required field: ${field}`);
    }
  }

  if (errors.length > 0) return errors; // Can't validate further

  // Schema version
  if (typeof c.schemaVersion !== "number") {
    errors.push(`schemaVersion must be a number, got ${typeof c.schemaVersion}`);
  }

  // Validate all address strings in nested objects
  function validateAddresses(obj: unknown, path: string): void {
    if (typeof obj === "string") {
      if (!isValidBase58Address(obj)) {
        errors.push(`Invalid base58 address at ${path}: "${obj}"`);
      }
    } else if (obj && typeof obj === "object" && !Array.isArray(obj)) {
      for (const [key, value] of Object.entries(obj as Record<string, unknown>)) {
        // Skip non-address fields
        if (["schemaVersion", "generatedAt", "cluster", "transferredAt", "metadata"].includes(key)) continue;
        if (value === null) continue; // null is allowed for optional fields (alt, squadsVault, transferredAt)
        validateAddresses(value, `${path}.${key}`);
      }
    }
  }

  // Validate programs
  validateAddresses(c.programs, "programs");

  // Validate mints
  validateAddresses(c.mints, "mints");

  // Validate pdas
  validateAddresses(c.pdas, "pdas");

  // Validate pools
  validateAddresses(c.pools, "pools");

  // Validate curvePdas
  validateAddresses(c.curvePdas, "curvePdas");

  // Validate hookAccounts
  validateAddresses(c.hookAccounts, "hookAccounts");

  // Validate treasury
  if (typeof c.treasury === "string" && !isValidBase58Address(c.treasury)) {
    errors.push(`Invalid treasury address: "${c.treasury}"`);
  }

  // Validate authority
  if (c.authority && typeof c.authority === "object") {
    const auth = c.authority as Record<string, unknown>;
    if (typeof auth.deployer === "string" && !isValidBase58Address(auth.deployer)) {
      errors.push(`Invalid authority.deployer address: "${auth.deployer}"`);
    }
    if (auth.squadsVault !== null && typeof auth.squadsVault === "string" && !isValidBase58Address(auth.squadsVault)) {
      errors.push(`Invalid authority.squadsVault address: "${auth.squadsVault}"`);
    }
  }

  // Validate alt (can be null)
  if (c.alt !== null && typeof c.alt === "string" && !isValidBase58Address(c.alt)) {
    errors.push(`Invalid ALT address: "${c.alt}"`);
  }

  return errors;
}
