/**
 * image-data.ts
 *
 * Auto-generated by scripts/optimize-images.mjs
 * DO NOT EDIT MANUALLY -- re-run the script to regenerate.
 *
 * Contains blur placeholder data URLs, overlay dimensions, and position
 * metadata for the factory scene. All positions are percentages of the
 * original 5568x3072 scene dimensions.
 */

/** Metadata for the scene background image */
export interface BackgroundData {
  /** Path to the default (1920w) background WebP */
  src: string;
  /** Tiny base64 blur placeholder for progressive loading */
  blurDataURL: string;
  /** Original scene width in pixels */
  width: number;
  /** Original scene height in pixels */
  height: number;
}

/** Metadata for a single overlay image */
export interface OverlayData {
  /** Path to the overlay WebP in public/ */
  src: string;
  /** Tiny base64 blur placeholder for progressive loading */
  blurDataURL: string;
  /** Cropped overlay width in pixels */
  width: number;
  /** Cropped overlay height in pixels */
  height: number;
  /** Left position as percentage of scene width (0-100) */
  left: number;
  /** Top position as percentage of scene height (0-100) */
  top: number;
  /** Width as percentage of scene width (0-100) */
  widthPct: number;
  /** Height as percentage of scene height (0-100) */
  heightPct: number;
  /** Whether the asset file exists (false for placeholders like swap-station) */
  available: boolean;
}

/** Complete scene data structure */
export interface SceneData {
  background: BackgroundData;
  overlays: Record<string, OverlayData>;
}

export const SCENE_DATA: SceneData = {
  background: {
    src: '/scene/background/factory-bg-1920.webp',
    blurDataURL: 'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJQBOmUABss+S7l+gy6oAA/tlVPRV8N59I9mOCxbhGbvcOKJw4pgBZZjtbjyfo0Rzax6VtJciK7JVzy3AAAA==',
    width: 5568,
    height: 3072,
  },
  overlays: {
    'banner': {
      src: '/scene/overlays/banner.webp',
      blurDataURL: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4WAoAAAAQAAAACQAAAwAAQUxQSCkAAAAAIlxdqpCSrI5mH5Oep5KblZeflHKTvraOs5uft8SaJb6Yb1lbYI+qPABWUDggKgAAALABAJ0BKgoABAAFQHwliAJ0ANzHVgAA+4d1W4eAuSIcFKwwmCcibsDAAA==',
      width: 836,
      height: 367,
      left: 42.58,
      top: 31.8,
      widthPct: 15.01,
      heightPct: 11.95,
      available: true,
    },
    'carnage-cauldron': {
      src: '/scene/overlays/carnage-cauldron.webp',
      blurDataURL: 'data:image/webp;base64,UklGRgABAABXRUJQVlA4WAoAAAAQAAAACQAADgAAQUxQSI0AAAABgFrbtmpnP/rMZJlJM0Mb32ENcagSFZlUgZIVK7TgovnBDhURERMAiBhG8a8YkYISAAHmhVDXAQCShPBZBDIgolpCNghBqi5vri1uL+Uk3yMNUuOlMqeqql8qXxpPNEhS580B9f/2N/hpkIbKcfaZumHofAgpe9cf5PvrKhIjMXa6EkuvOyGI2CpDkEUAVlA4IEwAAADwAQCdASoKAA8ABUB8JaACdAEWO1lllhgAzh43By7hCbe6y+bcpTb61zetR2137To40rJfQbWa7ZwuuoZ3Do1ztIDiMiLAqHCsPAAA',
      width: 832,
      height: 1261,
      left: 73.65,
      top: 57.88,
      widthPct: 14.94,
      heightPct: 41.05,
      available: true,
    },
    'connect-wallet': {
      src: '/scene/overlays/connect-wallet.webp',
      blurDataURL: 'data:image/webp;base64,UklGRsYAAABXRUJQVlA4WAoAAAAQAAAACQAACQAAQUxQSGUAAAAAADc4AAMAIlIAAgA3OgAEACNYAAIAOT4AAwAkVwADADk+AAkAH2IAAwA4S2Xe06fsnRAMte/7/////f90fP/7/Pz9+/z/2ur//Pz8+/r4/3ym//z////9/98lKtfixa+Xf24zAABWUDggOgAAANABAJ0BKgoACgAFQHwliAJ0AQ46Z6U0AP7MEkXxaLf3VAJAVhazVCgWd/+SorC0ly/qsotOJGPwAAA=',
      width: 1358,
      height: 1363,
      left: 64.71,
      top: 0,
      widthPct: 24.39,
      heightPct: 44.37,
      available: true,
    },
    'documentation-table': {
      src: '/scene/overlays/documentation-table.webp',
      blurDataURL: 'data:image/webp;base64,UklGRsQAAABXRUJQVlA4WAoAAAAQAAAACQAACAAAQUxQSFsAAAAA0ezs8PT2/5IAAY///f////7/aAAQ1v/8//78/vErAHv/+fv///z/ngBL//7/+c3bnjIAAsjBaGVcymEAAQC5qYmHmf/ZJgAd7sgkACRQj1wx2//nMQADAAAAAFZQOCBCAAAA0AEAnQEqCgAJAAVAfCUAToAbrm3MyHwA/kxn2hkHNVtc9mJHbzYHm6uFIl5KNt1pWBcUJVb24JpGlFyi4UlyAAAA',
      width: 1399,
      height: 1213,
      left: 10.61,
      top: 60.51,
      widthPct: 25.13,
      heightPct: 39.49,
      available: true,
    },
    'rewards-vat': {
      src: '/scene/overlays/rewards-vat.webp',
      blurDataURL: 'data:image/webp;base64,UklGRnwBAABXRUJQVlA4WAoAAAAQAAAACQAAGAAAQUxQSN0AAAABkHJt27HZuq9PY9tINpvd7GzbbSaxWcltmm1jM03atvXq2oqIUMEsfv6+GVSAbnlr8H0O1EDIbPhjCnVQI7pvggJfOgFRvcUUuAMVPDcOKXITGhUy7yjyVAXo0EBJ4YEXNGiiwO3sFiROzVDkVVkX4k9+UKHENsQtPaTEl086UPNYoMJP76fRSoWkzB4VJilR4pxKi6r/hqBFNSUqfJekRdU/5Wm3DjWUKLIBRqV3VKjwjdciZUWSZL7znvsx+oky7wUjJ8D6+VX/t3Ro0yxMww11RW5Q5dkBKg0AAABWUDggeAAAAPADAJ0BKgoAGQA/OYS5U68opaKwCAHgJwlmAJ0AGh0kTjgR+l26p2AA/nKyVL/IhFOhH5bdlWPEyT0SGtkZP+jtUL8f337KhgTmjtvowkNvI4Py0GMdYJ4hst57E6drs5GFHscHtdxA8+Ap9Ih0Bwh8UnkiBi1AAA==',
      width: 898,
      height: 2202,
      left: 20.24,
      top: 25.59,
      widthPct: 16.13,
      heightPct: 71.68,
      available: true,
    },
    'settings': {
      src: '/scene/overlays/settings.webp',
      blurDataURL: 'data:image/webp;base64,UklGRgABAABXRUJQVlA4WAoAAAAQAAAACQAADwAAQUxQSJ0AAAABgGNt2zHnGduzAs8C5swSlHTcgMqkSutUxh7MymVKtrZt53u/J9hERGTleBoG/N/wMAIzjAZ8frIOJgA40WxA7Vq7C/1kaSW/2QJfTd/Vt3xxw2nNVhxTNB+i4/z81KJ4EaYI30Q4BkXF4cnj281ipYVLi20DXL6hkFSPnKr/0o9f31ztzCCVK1HfXIDBYEBonWyDBUYLcjvTPhgAAFZQOCA8AAAA0AEAnQEqCgAQAAVAfCWQAnQAwviaDgAA/ujxcsnVgvbweoo2PQmEwJgqiaObuM4Bm6mOoc4ZGQS++SgA',
      width: 885,
      height: 1409,
      left: 0,
      top: 11.65,
      widthPct: 15.89,
      heightPct: 45.87,
      available: true,
    },
    'swap-station': {
      src: '/scene/overlays/swap-station.webp',
      blurDataURL: 'data:image/webp;base64,UklGRtAAAABXRUJQVlA4WAoAAAAQAAAACQAADAAAQUxQSHAAAAABgFvb1rLoLZpgUQDk3gGk7iGhO0TuVs1UMF3QwLi7fXLGioiIkCJv2rxSEmmhQTES6aP+piIt9N9YJPSCtaiwuOsHjOHc40jrdwCtYseYfxydYP8MhwhYsJaC85Uvpb748rresGDRgSiP++FgdUMBVlA4IDoAAADwAQCdASoKAA0ABUB8JQBOgCKXIeOSgwAA/gM2tiaFr2kxis51IS6yKloGk5Vi3FXoiIOM08FZAAAA',
      width: 999,
      height: 1347,
      left: 41.02,
      top: 46.09,
      widthPct: 17.94,
      heightPct: 43.85,
      available: true,
    },
    'wallet-connected': {
      src: '/scene/overlays/wallet-connected.webp',
      blurDataURL: 'data:image/webp;base64,UklGRsIAAABXRUJQVlA4WAoAAAAQAAAACQAACQAAQUxQSGUAAAAAADk5AAMAI1QAAgA5PAAEACRZAAIAO0AAAwAlWAADADtAAAoAIGMAAwA6TWbf06ntnhAMtvD7/////f90fv/7/Pz9+/z/2uz+/Pz8+/r4/32o//z////9/+AlK9jjxa+YgG4zAABWUDggNgAAAPABAJ0BKgoACgAFQHwliAJ0AQ5nH+5sAAD+zBI0jO++kgQIYKBO/SigEaEYaM7KLTiRj8AAAA==',
      width: 1358,
      height: 1363,
      left: 64.51,
      top: 0,
      widthPct: 24.39,
      heightPct: 44.37,
      available: true,
    },
  },
} as const;
