/**
 * image-data.ts
 *
 * Auto-generated by scripts/optimize-images.mjs
 * DO NOT EDIT MANUALLY -- re-run the script to regenerate.
 *
 * Contains blur placeholder data URLs, overlay dimensions, and position
 * metadata for the factory scene. All positions are percentages of the
 * original 5568x3072 scene dimensions.
 */

/** Metadata for the scene background image */
export interface BackgroundData {
  /** Path to the default (1920w) background WebP */
  src: string;
  /** Tiny base64 blur placeholder for progressive loading */
  blurDataURL: string;
  /** Original scene width in pixels */
  width: number;
  /** Original scene height in pixels */
  height: number;
}

/** Metadata for a single overlay image */
export interface OverlayData {
  /** Path to the overlay WebP in public/ */
  src: string;
  /** Tiny base64 blur placeholder for progressive loading */
  blurDataURL: string;
  /** Cropped overlay width in pixels */
  width: number;
  /** Cropped overlay height in pixels */
  height: number;
  /** Left position as percentage of scene width (0-100) */
  left: number;
  /** Top position as percentage of scene height (0-100) */
  top: number;
  /** Width as percentage of scene width (0-100) */
  widthPct: number;
  /** Height as percentage of scene height (0-100) */
  heightPct: number;
  /** Whether the asset file exists (false for placeholders like swap-station) */
  available: boolean;
}

/** Complete scene data structure */
export interface SceneData {
  background: BackgroundData;
  overlays: Record<string, OverlayData>;
}

export const SCENE_DATA: SceneData = {
  background: {
    src: '/scene/background/factory-bg-1920.webp',
    blurDataURL: 'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJQBOmUABss+S7l+gy6oAA/tlVPRV8N59I9mOCxbhGbvcOKJw4pgBZZjtbjyfo0Rzax6VtJciK7JVzy3AAAA==',
    width: 5568,
    height: 3072,
  },
  overlays: {
    'banner': {
      src: '/scene/overlays/banner-v2.webp',
      blurDataURL: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4WAoAAAAQAAAACQAAAwAAQUxQSCkAAAAAIlxdqpCSrI5mH5Oep5KblZeflHKTvraOs5uft8SaJb6Yb1lbYI+qPABWUDggKgAAALABAJ0BKgoABAAFQHwliAJ0ANzHVgAA+4d1W4eAuSIcFKwwmCcibsDAAA==',
      width: 836,
      height: 367,
      left: 42.58,
      top: 31.8,
      widthPct: 15.01,
      heightPct: 11.95,
      available: true,
    },
    'carnage-cauldron': {
      src: '/scene/overlays/carnage-cauldron.webp',
      blurDataURL: 'data:image/webp;base64,UklGRgIBAABXRUJQVlA4WAoAAAAQAAAACQAADgAAQUxQSI0AAAABgFrbtmpnP/rMZJlJM0Mb32ENcagSFZlUgZIVK7TgovnBDhURERMAiBhG8a8YkYISAAHmhVDXAQCShPBZBDIgolpCNghBqi5vri1uL+Uk3yMNUuOlMqeqql8qXxpPNEhS580B9f/2N/hpkIbKcfaZumHofAgpe9cf5PvrKhIjMXa6EkuvOyGI2CpDkEUAVlA4IE4AAADQAQCdASoKAA8ABUB8JZgCdAEWO1JHwADOHjcHLuEJt7rL5tylNvrXN61HbXftUAoK/qyGY3MHvKzOAkcpdC4gzbXbpzxIGEfgqGylAAA=',
      width: 832,
      height: 1261,
      left: 73.69,
      top: 58.04,
      widthPct: 14.94,
      heightPct: 41.05,
      available: true,
    },
    'connect-wallet': {
      src: '/scene/overlays/connect-wallet.webp',
      blurDataURL: 'data:image/webp;base64,UklGRsYAAABXRUJQVlA4WAoAAAAQAAAACQAACQAAQUxQSGUAAAAAADc4AAMAIlIAAgA3OgAEACNYAAIAOT4AAwAkVwADADk+AAkAH2IAAwA4S2Xe06fsnRAMte/7/////f90fP/7/Pz9+/z/2ur//Pz8+/r4/3ym//z////9/98lKtfixa+Xf24zAABWUDggOgAAANABAJ0BKgoACgAFQHwliAJ0AQ46Z6U0AP7MEkXxaLf3VAJAVhazVCgWd/+SorC0ly/qsotOJGPwAAA=',
      width: 1358,
      height: 1363,
      left: 64.71,
      top: 0,
      widthPct: 24.39,
      heightPct: 44.37,
      available: true,
    },
    'documentation-table': {
      src: '/scene/overlays/documentation-table.webp',
      blurDataURL: 'data:image/webp;base64,UklGRsIAAABXRUJQVlA4WAoAAAAQAAAACQAACAAAQUxQSFsAAAAA0ezs8PT2/5IAAY///f////7/aAAQ1v/8//78/vErAHv/+fv///z/ngBL//7/+c3bnjIAAsjBaGVcymEAAQC5qYmHmf/ZJgAd7sgkACRQj1wx2//nMQADAAAAAFZQOCBAAAAA0AEAnQEqCgAJAAVAfCUAToAbrna0PggA/cLzXX9OmWTyh63f0cMYxMSaXCodj4mgqFD3ojf2XP1kKPprV/gAAA==',
      width: 1399,
      height: 1213,
      left: 10.74,
      top: 60.51,
      widthPct: 25.13,
      heightPct: 39.49,
      available: true,
    },
    'rewards-vat': {
      src: '/scene/overlays/rewards-vat.webp',
      blurDataURL: 'data:image/webp;base64,UklGRoIBAABXRUJQVlA4WAoAAAAQAAAACQAAGAAAQUxQSN4AAAABkHNb27G5qq+xbbO1bVRWaXtK27btaiZ2lc6obdvJqyuKiABUHKs7taECYOnW6udoqAHux31Py28zoYrAsRkKfG0J+AyXUuAldcDpxAFFXoCqCkreUuRFABqooqjw0B7qqKbAqy31CBwYpsCjyU1IOLVPkZfO9SFi+zxF3j7Ti9wbAhV+fLuKZiokZS6oYIsSJZ7SVEcxJYqcgDpKKFHm88D/FX7t1UARJYpsgFraLcpU+NhlnooiizK/euxw7xNl5X44MsOMnj1Y+JYD9SQz/ShD9Uo3qKTbQgVqAABWUDggfgAAANADAJ0BKgoAGQA/OYa5U68pJaKwCAHgJwliAJ0AGilMLZv8lUVEAAD9dj3x71hM0D+9dhUECI/dQrXJD2z0H1mc27krlIqGR0hGHjwFpmwtfjvTcHzhcRy/tZFbFCGzkJuXmK/Gk0vjEN0yjEz2DtlGhdg4X82fBrH2fjdAAA==',
      width: 902,
      height: 2247,
      left: 20.11,
      top: 24.74,
      widthPct: 16.2,
      heightPct: 73.14,
      available: true,
    },
    'settings': {
      src: '/scene/overlays/settings.webp',
      blurDataURL: 'data:image/webp;base64,UklGRgABAABXRUJQVlA4WAoAAAAQAAAACQAADwAAQUxQSJ0AAAABgGNt2zHnGduzAs8C5swSlHTcgMqkSutUxh7MymVKtrZt53u/J9hERGTleBoG/N/wMAIzjAZ8frIOJgA40WxA7Vq7C/1kaSW/2QJfTd/Vt3xxw2nNVhxTNB+i4/z81KJ4EaYI30Q4BkXF4cnj281ipYVLi20DXL6hkFSPnKr/0o9f31ztzCCVK1HfXIDBYEBonWyDBUYLcjvTPhgAAFZQOCA8AAAA0AEAnQEqCgAQAAVAfCWQAnQAwviaDgAA/ujxcsnVgvbweoo2PQmEwJgqiaObuM4Bm6mOoc4ZGQS++SgA',
      width: 885,
      height: 1409,
      left: 0,
      top: 11.65,
      widthPct: 15.89,
      heightPct: 45.87,
      available: true,
    },
    'swap-station': {
      src: '/scene/overlays/swap-station.webp',
      blurDataURL: 'data:image/webp;base64,UklGRtAAAABXRUJQVlA4WAoAAAAQAAAACQAADAAAQUxQSHAAAAABgFvb1rLoLZpgUQDk3gGk7iGhO0TuVs1UMF3QwLi7fXLGioiIkCJv2rxSEmmhQTES6aP+piIt9N9YJPSCtaiwuOsHjOHc40jrdwCtYseYfxydYP8MhwhYsJaC85Uvpb748rresGDRgSiP++FgdUMBVlA4IDoAAADwAQCdASoKAA0ABUB8JQBOgCKKdURHXoAA/pvRoE8j6ewl0+6+hNKEzql9HNWR8WRKNSAS3ZCzNsYA',
      width: 999,
      height: 1347,
      left: 41.04,
      top: 46.22,
      widthPct: 17.94,
      heightPct: 43.85,
      available: true,
    },
  },
} as const;
